modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/lukebemish/cobbled_paths/issues"
license = "LGPL v3"

[[mods]]
modId = "cobbled_paths"
version = "${version}"
displayName = "Cobbled Paths"
authors = "Luke Bemish"
description = '''
Adds various cobbled and paved paths.
'''
logoFile = "icon.png"

[[dependencies.cobbled_paths]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbled_paths]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbled_paths]]
modId = "architectury"
mandatory = true
versionRange = "[3.4.9,)"
ordering = "AFTER"
side = "BOTH"